apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps
        imagePullPolicy: Never
        livenessProbe:
          tcpSocket:
            port: 21
          initialDelaySeconds: 4
          periodSeconds: 4

---

apiVersion: v1
kind: Service
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  ports:
  - name: ftps
    port: 21
    protocol: TCP
    targetPort: 21
  - name: download
    port: 30000
    protocol: TCP
    targetPort: 30000
  - name: download1
    port: 30001
    protocol: TCP
    targetPort: 30001
  - name: download2
    port: 30002
    protocol: TCP
    targetPort: 30002
  - name: download3
    port: 30003
    protocol: TCP
    targetPort: 30003
  - name: download4
    port: 30004
    protocol: TCP
    targetPort: 30004
  selector:
    app: ftps
  type: LoadBalancer
  loadBalancerIP: 192.168.99.172
